# General ProGuard rules for Winlator

# Keep all classes in com.winlator that have native methods
-keepclasseswithmembers class com.winlator.** {
    native <methods>;
}

# Keep specific classes and methods accessed from native code (JNI callbacks)
-keep class com.winlator.xenvironment.components.VirGLRendererComponent {
    private void killConnection(int);
    private void flushFrontbuffer(int, int);
}

-keep class com.winlator.xenvironment.components.VortekRendererComponent {
    private int getWindowWidth(int);
    private int getWindowHeight(int);
    private long getWindowHardwareBuffer(int, boolean);
    private void updateWindowContent(int);
}

-keep class com.winlator.xenvironment.components.VortekRendererComponent$Options { *; }

-keep class com.winlator.xserver.extensions.GLXExtension {
    private short[] getWindowSize(int);
    private void clearWindowContent(int);
    private boolean updateWindowContent(int, short, short, boolean);
    private long getGLXContextPtr(int, int);
}

-keep class com.winlator.xconnector.XConnectorEpoll {
    private void handleConnectionShutdown(java.lang.Object);
    private com.winlator.xconnector.ConnectedClient handleNewConnection(long, int);
    private void handleExistingConnection(long);
    private void killAllConnections();
}

-keep class com.winlator.renderer.GPUImage {
    private void setStride(short);
    private void setNativeHandle(int);
}

# Keep other JNI-related classes
-keep class com.winlator.core.GPUHelper { *; }
-keep class com.winlator.core.WineRegistryEditor { *; }
-keep class com.winlator.xserver.Pixmap { *; }
-keep class com.winlator.xserver.Drawable { *; }
-keep class com.winlator.sysvshm.SysVSharedMemory { *; }

# Keep classes used by dependencies
-keep class com.github.luben.zstd.** { *; }
-keep class org.tukaani.xz.** { *; }
-keep class org.apache.commons.compress.** {
    public protected <methods>;
    public protected <fields>;
}

# Keep XServer and its members as it's the core of the app
-keep class com.winlator.xserver.XServer { *; }

# Prevent obfuscation to make debugging easier
-dontobfuscate

# Rules generated by R8 for missing classes
-dontwarn org.brotli.dec.BrotliInputStream
-dontwarn org.objectweb.asm.AnnotationVisitor
-dontwarn org.objectweb.asm.Attribute
-dontwarn org.objectweb.asm.ClassReader
-dontwarn org.objectweb.asm.ClassVisitor
-dontwarn org.objectweb.asm.FieldVisitor
-dontwarn org.objectweb.asm.Label
-dontwarn org.objectweb.asm.MethodVisitor
-dontwarn org.objectweb.asm.Type
